### ISSUE TITLE
坚果云似乎不让下载了

### ISSUE THREAD

**Issue by XinZheng-SH** [niudai/How-to-be-a-good-programmer#10]
我点击各个链接，都显示账户异常已锁定，请大佬查看一下。

**Comment by William-Wang1988** [comment]
CSAPP中文版无法下载

**Comment by LittleNewton** [comment]
链接已经恢复。

我询问了坚果云的工作人员，他们说：

> 针对您的问题回复如下:
您好，请问是有什么提示呢？是链接不能打开下载了吗？
如果使用分享链接分享文件给非坚果云用户下载 （即分享链接的权限设置的是“任何人，包括未注册用户”）， **这样非坚果云用户下载时产生的流量也是算在分享链接的拥有者账户的流量里面的，如果一段时间内有很多人下载，就会导致系统判断账号有风险，从而触发系统保护。**
建议您修改一下分享链接的权限，修改为注册用户，谢谢
坚果云客户支持团队 

所以我把链接权限修改了。这样做产生的好处就是链接全部可用，然而负面影响就是流量消耗全都转移到你们个人账户上。

建议：

- 注册一个坚果云账户。我个人认为，注册账户的痛苦，比忍受百度与你100K的速度要好多了。
- 坚果云免费账号，如无必要，请勿下载不会看的书。（免费账号上传1G/月，下载3G/每月，这个库里的书应该是3G多，或者你找一个每月月底，如31号，下载一部分，然后第二天再下载一部分，就OK了）
- 坚果云高级版账号，请随意下载。

后期如果有任何问题，请开Issue进行套路。
