### ISSUE TITLE
这里是算法4的非扫描中文数字版，应该可读性比OCR版好一些

### ISSUE THREAD

**Issue by KeyAI** [niudai/How-to-be-a-good-programmer#14]
https://www.jianguoyun.com/p/DVcuIcUQmbzzBxic254D

**Comment by Liny927** [comment]
> https://www.jianguoyun.com/p/DVcuIcUQmbzzBxic254D

这个链接是只读的呀, 无法下载.. 可以分享下载吗? 谢谢!!

**Comment by KeyAI** [comment]
> > https://www.jianguoyun.com/p/DVcuIcUQmbzzBxic254D
> 
> 这个链接是只读的呀, 无法下载.. 可以分享下载吗? 谢谢!!

已经开启了下载权限，不好意思之前没有注意到设置了不可下载。另附文件。
[算法-第4版.pdf](https://github.com/niudai/How-to-be-a-good-programmer/files/5170133/-.4.pdf)
