### ISSUE TITLE
APUE用法上的疑问

### ISSUE THREAD

**Issue by kentzhang-geek** [niudai/How-to-be-a-good-programmer#33]
那本书感觉更像一本工具书。讲解了Unix下面各种C API的用法和机制。
现在基本上也没法直接拿APUE来指导Linux编程，APUE下面没讲一些Linux特有的接口和机制的，比如epoll，然而这些在Linux下面又很重要。

**Comment by sumu108** [comment]
真是个可爱的小调皮鬼呢！

**Comment by empiregeneral** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
