### ISSUE TITLE
关于机械工业出版的黑皮书系列

### ISSUE THREAD

**Issue by JIeJaitt** [niudai/How-to-be-a-good-programmer#36]
请问机械工业出版的黑皮书系列这些书都是没有官方提供的参考答案的嘛？课后作业特别是一个编程大作业我觉得是比较难的

**Comment by sumu108** [comment]
真是个可爱的小调皮鬼呢！

**Comment by sumu108** [comment]
真是个可爱的小调皮鬼呢！

**Comment by empiregeneral** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sumu108** [comment]
真是个可爱的小调皮鬼呢！

**Comment by empiregeneral** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by LittleNewton** [comment]
@empiregeneral 
请关闭 QQ 邮箱的自动回复，因为这对 GitHub issue 的解决没有帮助。可以设置邮件自动处理规则。
