### ISSUE TITLE
789VPN网址失效

### ISSUE THREAD

**Issue by zedding-7** [niudai/How-to-be-a-good-programmer#6]

**Comment by Miracle-zhong** [comment]
How to download.

**Comment by zedding-7** [comment]
> How to download.

I could visit 789vpn4.com/ but failed to download.
You can try another vpn : www.qiujiasu.cloud/ it's working well and cheaper.

**Comment by zedding-7** [comment]
> How to download.
I could visit 789vpn4.com/ but failed to download.
You can try another vpn : www.qiujiasu.cloud/ it's working well and cheaper.
